english_to_portuguese_dictionary = {
    'aircraft carrier': 'porta-aviões',
    'airplane': 'avião',
    'alarm clock': 'despertador',
    'ambulance': 'ambulância',
    'angel': 'anjo',
    'animal migration': 'migração animal',
    'ant': 'formiga',
    'anvil': 'bigorna',
    'apple': 'maçã',
    'arm': 'braço',
    'asparagus': 'aspargo',
    'axe': 'machado',
    'backpack': 'mochila',
    'banana': 'banana',
    'bandage': 'curativo',
    'barn': 'celeiro',
    'baseball bat': 'taco de beisebol',
    'baseball': 'beisebol',
    'basket': 'cesta',
    'basketball': 'basquetebol',
    'bat': 'morcego',
    'bathtub': 'banheira',
    'beach': 'praia',
    'bear': 'urso',
    'beard': 'barba',
    'bed': 'cama',
    'bee': 'abelha',
    'belt': 'cinto',
    'bench': 'banco',
    'bicycle': 'bicicleta',
    'binoculars': 'binóculos',
    'bird': 'pássaro',
    'birthday cake': 'bolo de aniversário',
    'blackberry': 'amora',
    'blueberry': 'mirtilo',
    'book': 'livro',
    'boomerang': 'bumerangue',
    'bottlecap': 'tampa de garrafa',
    'bowtie': 'gravata borboleta',
    'bracelet': 'pulseira',
    'brain': 'cérebro',
    'bread': 'pão',
    'bridge': 'ponte',
    'broccoli': 'brócolis',
    'broom': 'vassoura',
    'bucket': 'balde',
    'bulldozer': 'escavadeira',
    'bus': 'ônibus',
    'bush': 'arbusto',
    'butterfly': 'borboleta',
    'cactus': 'cacto',
    'cake': 'bolo',
    'calculator': 'calculadora',
    'calendar': 'calendário',
    'camel': 'camelo',
    'camera': 'câmera',
    'camouflage': 'camuflagem',
    'campfire': 'fogueira',
    'candle': 'vela',
    'cannon': 'canhão',
    'canoe': 'canoa',
    'car': 'carro',
    'carrot': 'cenoura',
    'castle': 'castelo',
    'cat': 'gato',
    'ceiling fan': 'ventilador de teto',
    'cell phone': 'celular',
    'cello': 'violoncelo',
    'chair': 'cadeira',
    'chandelier': 'lustre',
    'lustre': 'brilho',
    'circle': 'círculo',
    'clarinet': 'clarinete',
    'clock': 'relógio',
    'cloud': 'nuvem',
    'coffee cup': 'xícara de café',
    'compass': 'bússola',
    'computer': 'computador',
    'cookie': 'biscoito',
    'cooler': 'geladeira',
    'couch': 'sofá',
    'cow': 'vaca',
    'crab': 'caranguejo',
    'crayon': 'giz de cera',
    'crocodile': 'crocodilo',
    'crown': 'coroa',
    'cruise ship': 'cruzeiro',
    'cup': 'copo',
    'diamond': 'diamante',
    'dishwasher': 'lava-louças',
    'diving board': 'prancha de mergulho',
    'dog': 'cachorro',
    'dolphin': 'golfinho',
    'donut': 'rosquinha',
    'door': 'porta',
    'dragon': 'dragão',
    'dresser': 'cômoda',
    'drill': 'broca',
    'drums': 'bateria',
    'duck': 'pato',
    'dumbbell': 'halter',
    'ear': 'orelha',
    'elbow': 'cotovelo',
    'elephant': 'elefante',
    'envelope': 'envelope',
    'eraser': 'borracha',
    'eye': 'olho',
    'eyeglasses': 'óculos',
    'face': 'cara',
    'fan': 'ventilador',
    'feather': 'pena',
    'fence': 'cerca',
    'finger': 'dedo',
    'fire hydrant': 'hidrante',
    'fireplace': 'lareira',
    'firetruck': 'caminhão de bombeiros',
    'fish': 'peixe',
    'flamingo': 'flamingo',
    'flashlight': 'lanterna',
    'flip flops': 'chinelo',
    'floor lamp': 'luminária de piso',
    'flower': 'flor',
    'flying saucer': 'disco voador',
    'foot': 'pé',
    'fork': 'garfo',
    'frog': 'rã',
    'frying pan': 'frigideira',
    'garden hose': 'mangueira de jardim',
    'garden': 'jardim',
    'giraffe': 'girafa',
    'goatee': 'cavanhaque',
    'golf club': 'clube de Golf',
    'grapes': 'uva',
    'grass': 'grama',
    'guitar': 'violão',
    'hamburger': 'hamburger',
    'hammer': 'martelo',
    'hand': 'mão',
    'harp': 'harpa',
    'hat': 'chapéu',
    'headphones': 'fone de ouvido',
    'hedgehog': 'ouriço',
    'helicopter': 'helicóptero',
    'helmet': 'capacete',
    'hexagon': 'hexágono',
    'hockey puck': 'disco de hóquei',
    'hockey stick': 'taco de hóquei',
    'horse': 'cavalo',
    'hospital': 'hospital',
    'hot air balloon': 'balão',
    'hot dog': 'cachorro quente',
    'hot tub': 'jacuzzi',
    'hourglass': 'ampulheta',
    'house plant': 'planta de casa',
    'house': 'casa',
    'hurricane': 'furacão',
    'ice cream': 'sorvete',
    'jacket': 'jaqueta',
    'jail': 'cadeia',
    'kangaroo': 'canguru',
    'key': 'key',
    'keyboard': 'teclado',
    'knee': 'joelho',
    'knife': 'faca',
    'ladder': 'escada',
    'lantern': 'lanterna',
    'laptop': 'notebook',
    'leaf': 'folha',
    'leg': 'perna',
    'light bulb': 'lâmpada',
    'lighter': 'isqueiro',
    'lighthouse': 'farol',
    'lightning': 'relâmpago',
    'line': 'linha',
    'lion': 'leão',
    'lipstick': 'batom',
    'lobster': 'lagosta',
    'lollipop': 'pirulito',
    'mailbox': 'caixa de correio',
    'map': 'mapa',
    'marker': 'marcador',
    'matches': 'partida',
    'megaphone': 'megafone',
    'mermaid': 'sereia',
    'microphone': 'microfone',
    'microwave': 'micro-ondas',
    'monkey': 'macaco',
    'moon': 'lua',
    'mosquito': 'mosquito',
    'motorbike': 'moto',
    'mountain': 'montanha',
    'mouse': 'rato',
    'moustache': 'bigode',
    'mouth': 'boca',
    'mug': 'caneca',
    'mushroom': 'cogumelo',
    'nail': 'unha',
    'necklace': 'colar',
    'nose': 'nariz',
    'ocean': 'oceano',
    'octagon': 'octógono',
    'octopus': 'polvo',
    'onion': 'cebola',
    'oven': 'forno',
    'owl': 'coruja',
    'paint can': 'lata de tinta',
    'paintbrush': 'pincel',
    'palm tree': 'palmeira',
    'panda': 'panda',
    'pants': 'calça',
    'paper clip': 'clipe',
    'parachute': 'paraquedas',
    'parrot': 'parrot',
    'passport': 'passaporte',
    'peanut': 'amendoim',
    'pear': 'pera',
    'peas': 'ervilha',
    'pencil': 'lápis',
    'penguin': 'pinguim',
    'piano': 'piano',
    'pickup truck': 'caminhonete',
    'picture frame': 'moldura',
    'pig': 'porco',
    'pillow': 'travesseiro',
    'pineapple': 'abacaxi',
    'pizza': 'pizza',
    'pliers': 'alicate',
    'police car': 'carro de polícia',
    'pond': 'lagoa',
    'pool': 'piscina',
    'popsicle': 'picolé',
    'postcard': 'cartão postal',
    'potato': 'batata',
    'power outlet': 'tomada',
    'purse': 'bolsa',
    'rabbit': 'coelho',
    'raccoon': 'guaxinim',
    'radio': 'rádio',
    'rain': 'chuva',
    'rainbow': 'arco-íris',
    'rake': 'ancinho',
    'remote control': 'controle remoto',
    'rhinoceros': 'rinoceronte',
    'rifle': 'rifle',
    'river': 'rio',
    'roller coaster': 'montanha russa',
    'rollerskates': 'skate',
    'sailboat': 'barco à vela',
    'sandwich': 'sanduíche',
    'saw': 'serra',
    'saxophone': 'saxofone',
    'school bus': 'escolar',
    'scissors': 'tesouras',
    'scorpion': 'escorpião',
    'screwdriver': 'chave de fenda',
    'sea turtle': 'tartaruga marinha',
    'see saw': 'gangorra',
    'shark': 'tubarão',
    'sheep': 'ovelha',
    'shoe': 'sapato',
    'shorts': 'calção',
    'shovel': 'pá',
    'sink': 'pia',
    'skateboard': 'skate',
    'skull': 'crânio',
    'skyscraper': 'skyscraper',
    'sleeping bag': 'saco de dormir',
    'smiley face': 'cara feliz',
    'snail': 'caracol',
    'snake': 'serpente',
    'snorkel': 'snorkel',
    'snowflake': 'floco de neve',
    'snowman': 'boneco de neve',
    'soccer ball': 'bola de futebol',
    'sock': 'meia',
    'speedboat': 'lancha',
    'spider': 'aranha',
    'spoon': 'colher',
    'spreadsheet': 'planilha',
    'square': 'quadrado',
    'squiggle': 'rabisco',
    'squirrel': 'esquilo',
    'stairs': 'escadas',
    'star': 'estrela',
    'steak': 'bife',
    'stereo': 'estéreo',
    'stethoscope': 'estetoscópio',
    'stitches': 'pontos',
    'stop sign': 'placa de pare',
    'stove': 'fogão',
    'strawberry': 'morango',
    'streetlight': 'poste de luz',
    'string bean': 'vagem',
    'submarine': 'submarino',
    'suitcase': 'mala',
    'sun': 'sol',
    'swan': 'cisne',
    'sweater': 'suéter',
    'swing set': 'balanço',
    'sword': 'espada',
    'syringe': 'seringa',
    't-shirt': 'camiseta',
    'table': 'mesa',
    'teapot': 'bule de chá',
    'teddy-bear': 'ursinho de pelúcia',
    'telephone': 'telefone',
    'television': 'televisão',
    'tennis racquet': 'raquete de tênis',
    'tent': 'barraca',
    'The Eiffel Tower': 'torre Eiffel',
    'The Great Wall of China': 'Grande Muralha da China',
    'The Mona Lisa': 'Mona Lisa',
    'tiger': 'tigre',
    'toaster': 'torradeira',
    'toe': 'dedo do pé',
    'toilet': 'banheiro',
    'tooth': 'dente',
    'toothbrush': 'escova de dente',
    'toothpaste': 'pasta de dente',
    'tornado': 'tornado',
    'tractor': 'trator',
    'traffic light': 'traffic light',
    'train': 'trem',
    'tree': 'árvore',
    'triangle': 'triângulo',
    'trombone': 'trombone',
    'truck': 'caminhão',
    'trumpet': 'trompete',
    'umbrella': 'guarda-chuva',
    'underwear': 'roupas íntimas',
    'van': 'van',
    'vase': 'vaso',
    'violin': 'violino',
    'washing machine': 'máquina de lavar',
    'watermelon': 'melancia',
    'waterslide': 'toboágua',
    'whale': 'baleia',
    'wheel': 'roda',
    'windmill': 'moinho de vento',
    'wine bottle': 'garrafa de vinho',
    'wine glass': 'taça de vinho',
    'wristwatch': 'relógio de pulso',
    'yoga': 'ioga',
    'zebra': 'zebra',
    'zigzag': 'ziguezague',
    'church': 'igreja',
}